manual installation
-------------------

wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
---------------------------------------

Install the SDK
----------------
sudo apt-get update && \
sudo apt-get install -y dotnet-sdk-6.0

Install the runtime
-------------------
sudo apt-get update && \
sudo apt-get install -y aspnetcore-runtime-6.0

-------------------------------------------------------
---
- name: installing dotnet core  on ubuntu
  hosts: all
  tasks:
    - name: Download MS product repository
      get_url:
        url: wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: Install MS product repository
      apt: deb=/tmp/packages-microsoft-prod.deb
      become: true
    - name: Make sure HTTPS is supported by apt
      apt:
        name: apt-transport-https
        state: present
        update_cache: yes
      become: true
    - name: Install .NET Core SDK
      apt:
        name: dotnet-sdk-6.0
        state: present
        update_cache: yes
      become: true

